import pygame
import math
import heapq
import random
from settings import *

def heuristic(a, b):
    """Calculates Euclidean distance as the heuristic function for A*."""
    return math.sqrt((a[0] - b[0])**2 + (a[1] - b[1])**2)

def a_star(grid, start, goal):
    """
    Implementation of the A* (A-Star) pathfinding algorithm.
    Finds the shortest path from start to goal on a 2D grid map.
    """
    rows, cols = len(grid), len(grid[0])
    open_list = []
    heapq.heappush(open_list, (0, start))
    came_from = {}
    g_score = {start: 0}
    f_score = {start: heuristic(start, goal)}

    while open_list:
        current = heapq.heappop(open_list)[1]
        if current == goal:
            path = []
            while current in came_from:
                path.append(current)
                current = came_from[current]
            return path[::-1]

        for dx, dy in [(0, 1), (0, -1), (1, 0), (-1, 0)]:
            neighbor = (current[0] + dx, current[1] + dy)
            if 0 <= neighbor[0] < cols and 0 <= neighbor[1] < rows: 
                if grid[neighbor[1]][neighbor[0]] == 1: continue
                tentative_g_score = g_score[current] + 1
                if neighbor not in g_score or tentative_g_score < g_score[neighbor]:
                    came_from[neighbor] = current
                    g_score[neighbor] = tentative_g_score
                    f_score[neighbor] = tentative_g_score + heuristic(neighbor, goal)
                    if neighbor not in [i[1] for i in open_list]:   
                        heapq.heappush(open_list, (f_score[neighbor], neighbor))
    return None

class Item:
    """Manages static game items (Key, Exit, Energy, Armor, Health)."""
    def __init__(self, x, y, type, dropped=False):
        self.x, self.y, self.type = x, y, type
        self.alive, self.dist, self.angle = True, 0, 0
        # Items that go into inventory for manual use
        self.usable = type in ['energy', 'health']
        self.collectible = type not in ['exit']
        
        # Animation properties
        self.dropped = dropped
        self.drop_timer = 30 if dropped else 0 # Animation frames for "popping out"
        self.bob_timer = random.random() * math.pi * 2 # Random start phase for bobbing

    def update_animation(self):
        """Updates the visual bounce/bobbing effect."""
        if self.drop_timer > 0:
            self.drop_timer -= 1
        self.bob_timer += 0.05

class Trap:
    """Manages traps (Spikes, Mimics)."""
    def __init__(self, x, y, type, player):
        self.x, self.y, self.type, self.player = x, y, type, player
        self.alive = True
        self.dist, self.angle = 0, 0
        self.radius = 8
        self.damage = 15
        self.triggered = False
        self.trigger_timer = 0
        self.cooldown = 0

    def update(self):
        if not self.alive: return
        
        dist_to_player = math.sqrt((self.player.x - self.x)**2 + (self.player.y - self.y)**2)
        
        if self.type == 'spike':
            if dist_to_player < 12 and self.cooldown <= 0:
                self.player.take_damage(self.damage)
                self.cooldown = 60 # 1 second cooldown
                self.triggered = True
                self.trigger_timer = 15
            
            if self.cooldown > 0:
                self.cooldown -= 1
            if self.trigger_timer > 0:
                self.trigger_timer -= 1
            else:
                self.triggered = False

        elif self.type == 'mimic':
            if dist_to_player < 20:
                # Transform into a monster!
                self.alive = False
                return 'transform'
        return None

class Monster:
    """
    Manages monster AI logic.
    Utilizes the A* algorithm to track and chase the player.
    """
    def __init__(self, x, y, map, player):
        self.x, self.y, self.map, self.player = x, y, map, player
        self.radius, self.moveSpeed = 4, 0.5
        self.path, self.update_path_timer, self.hp, self.alive = [], 0, 30, True

    def take_damage(self, amount, items_list=None):
        """Reduces monster HP and updates survival status. Potentially drops items."""
        self.hp -= amount
        if self.hp <= 0: 
            self.alive = False
            if items_list is not None:
                # Drop reward
                chance = random.random()
                if chance < 0.3: # 30% chance to drop energy
                    items_list.append(Item(self.x, self.y, 'energy', dropped=True))
                elif chance < 0.5: # 20% chance to drop armor (total 50% drop rate)
                    items_list.append(Item(self.x, self.y, 'armor', dropped=True))

    def update(self, qtree=None):
        """Updates monster movement based on the path generated by A*."""
        if not self.alive: return
        dist_to_player = math.sqrt((self.player.x - self.x)**2 + (self.player.y - self.y)**2)
        if dist_to_player < 15:
            self.player.take_damage(0.1)
            return

        self.update_path_timer += 1
        if self.update_path_timer >= 30:
            start_grid = (int(self.x // TILESIZE), int(self.y // TILESIZE))
            goal_grid = (int(self.player.x // TILESIZE), int(self.player.y // TILESIZE))
            self.path = a_star(self.map.grid, start_grid, goal_grid)
            self.update_path_timer = 0

        if self.path:
            target_grid = self.path[0]
            target_x, target_y = target_grid[0] * TILESIZE + TILESIZE // 2, target_grid[1] * TILESIZE + TILESIZE // 2    
            dx, dy = target_x - self.x, target_y - self.y
            dist_to_target = math.sqrt(dx**2 + dy**2)
            
            if dist_to_target > 2:
                new_vx = (dx / dist_to_target) * self.moveSpeed
                new_vy = (dy / dist_to_target) * self.moveSpeed
                
                # --- COLLISION AVOIDANCE WITH OTHER MONSTERS USING QUADTREE ---
                if qtree:
                    from quadtree import Rect
                    # Search for monsters in a small radius
                    nearby = qtree.query(Rect(self.x, self.y, 20, 20))
                    for p in nearby:
                        other = p.data
                        if other is self or not hasattr(other, 'hp'): continue
                        
                        dist_sq = (self.x - other.x)**2 + (self.y - other.y)**2
                        if dist_sq < (self.radius + other.radius)**2:
                            # Push away from other monster
                            push_x = self.x - other.x
                            push_y = self.y - other.y
                            push_dist = math.sqrt(push_x**2 + push_y**2)
                            if push_dist > 0:
                                new_vx += (push_x / push_dist) * 0.2
                                new_vy += (push_y / push_dist) * 0.2

                self.x += new_vx
                self.y += new_vy
            else: self.path.pop(0)

    def render_on_minimap(self, screen):
        """Displays monster position and its current A* path on the Mini-map (Top-Right)."""
        if not self.alive: return
        scale = MINIMAP_SCALE
        offset_x = WINDOW_WIDTH - (COLS * TILESIZE * scale) - 10
        offset_y = 10
        
        mx = offset_x + self.x * scale
        my = offset_y + self.y * scale
        
        pygame.draw.circle(screen, (0, 0, 255), (int(mx), int(my)), 2)
        
        # Draw a short line representing the next step in the path
        if self.path:
            target = self.path[0]
            tx = offset_x + (target[0] * TILESIZE + TILESIZE // 2) * scale
            ty = offset_y + (target[1] * TILESIZE + TILESIZE // 2) * scale
            pygame.draw.line(screen, (0, 255, 0), (mx, my), (tx, ty), 1)
